# Generated by Django 2.0.4 on 2018-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BroadviewCOSS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='mainframe',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['last_update']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='mainframe',
            name='host',
            field=models.PositiveIntegerField(default=9876),
        ),
        migrations.AlterField(
            model_name='mainframe',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, '正常'), (1, '无法连接'), (2, '未知')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
