# Generated by Django 2.0.4 on 2018-06-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BroadviewCOSS', '0002_auto_20180604_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='details',
        ),
    ]
