# Generated by Django 2.0.4 on 2018-06-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BroadviewCOSS', '0004_auto_20180605_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='BroadviewCOSS.Category')),
            ],
            options={
                'db_table': 'TaskCategory',
            },
        ),
        migrations.CreateModel(
            name='TaskMainframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainframe', models.ForeignKey(db_column='mainframe', on_delete=django.db.models.deletion.CASCADE, to='BroadviewCOSS.Mainframe')),
            ],
            options={
                'db_table': 'TaskMainframe',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mainframe',
        ),
        migrations.AddField(
            model_name='taskmainframe',
            name='task',
            field=models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, to='BroadviewCOSS.Task'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='task',
            field=models.ForeignKey(db_column='task', on_delete=django.db.models.deletion.CASCADE, to='BroadviewCOSS.Task'),
        ),
    ]
