# Generated by Django 2.0.4 on 2018-06-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BroadviewCOSS', '0005_auto_20180605_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='details',
            new_name='description',
        ),
    ]
